### ISSUE TITLE
Add members to Brisbane Team

### ISSUE THREAD

**Issue by orchid00** [rladies/meetup-presentations_brisbane#18]
Hi @hfrick, 
I would like to add new members to this team, could you help me with that please?
Or if you can change my setting I will add them. 
The accounts are @vmurigneu @seaCatKim 

thanks for your help!

**Comment by hfrick** [comment]
@orchid00 you have admin permission for the repo so you should be able to add collaborators to the repo. adding members to the team means adding members to the org so that's something a admin for the org has to do. I've sent invites just now! 

Welcome @vmurigneu and @seaCatKim !

**Comment by orchid00** [comment]
Thanks @hfrick 

For the record collaborators to the repo can be added from Settings > Manage Access.

**Comment by seaCatKim** [comment]
Hi @hfrick, sorry think I let the invite expire... pretty new to GitHub.

Could you reinvite myself and another user @cdkuempel? Paula and Valentine will be stepping down for a bit so would be nice to have some redundancy while they are gone.

**Comment by hfrick** [comment]
@seaCatKim invite resent! ✅ 
@cdkuempel hi! 👋

**Comment by seaCatKim** [comment]
Invite accepted. Thank you! 🤗
